#!/bin/bash

outfile=ts/barlines-modern.ts
touch $outfile

echo "`date`: Generating $outfile"
echo "// Generated by $0 at `date`" > $outfile
echo "export const scorebars_modern = [" >> $outfile
for i in svg/modern/spem-choir*.svg; do
  echo -n "  [" >> $outfile
  grep -B 2 '<tspan>[0-9]*</tspan>' "$i" | sed -n 's/^.*translate(\([^,]*\),.*$/\1/p' | sort -n | sed 's/$/, /' | tr -d '\n' >> $outfile
  echo "]," >> $outfile
done
echo "];" >> $outfile


echo "`date`: Removing height and width from header of spem-choir*.svg"
for i in svg/modern/spem-choir*.svg; do
  sed -i '' -E '1,1s/ height="[0-9.]+[a-zA-Z]*"//g; 1,1s/ width="[0-9.]+[a-zA-Z]*"//g' "$i"
done